modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="umapi"
version="${version}"
displayName="UMAPI"
authors="SpilledSoup"
description='''Universal Minecraft API'''

[[dependencies.umapi]]
modId="forge"
mandatory=true
versionRange="[40.3.12,)"
ordering="NONE"
side="BOTH"

[[dependencies.umapi]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
